### PR TITLE
Use Java 11 (latest LTS)

### PR DESCRIPTION
**Pull request by brunoborges**
You should really use the latest Java LTS release if you want to do a fair benchmark.

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@brunoborges Thank you for noticing, you're absolutely right! Could you please also update the Dockerfile in `kotlin_grpc` and the `clean.sh` script?

**Comment by brunoborges** [comment]
@LesnyRumcajs a few things added here:

1. Use Java 11
1. Set Java benchs to use up to 70% available RAM for the JVM Heap size
1. Increase duration to 10min. This is because the JVM will improve performance over time. 30s is not enough for a realistic runtime/language comparison benchmark.
1. Limit memory to 512m by default

There is another thing to consider: the JVM has multiple Garbage Collectors. With a single CPU, the JVM will default to the SerialGC [1]. For realistic comparisons, you should consider using two CPUs for the JVM-based workloads.

And for runtimes that are single threaded by nature (e.g. Node) maybe consider a slightly different approach to compare: run two containers for Node at the same time and a third for LB, in a way that this set up equals to the JVM workload in terms of CPU and memory.

[1] https://www.baeldung.com/jvm-garbage-collectors

**Comment by LesnyRumcajs** [comment]
>     1. Use Java 11
Sounds good!

>     2. Set Java benchs to use up to 70% available RAM for the JVM Heap size
Sounds good!

>     3. Increase duration to 10min. This is because the JVM will improve performance over time. 30s is not enough for a realistic runtime/language comparison benchmark.
Those `30s` were anyway used only for CI, to not abuse Github Actions. For actual benchmarks we we used at least 2 minutes. But I agree, increasing it brings it closer to real-world scenario.

>     4. Limit memory to 512m by default
A valid constraint, though it would (on our hardware) probably impact only Micronaut benchmark.

>     5. Default to 2 cores
> 
> 
> There is another thing to consider: the JVM has multiple Garbage Collectors. With a single CPU, the JVM will default to the SerialGC [1]. For realistic comparisons, you should consider using two CPUs for the JVM-based workloads so it picks a better one such as ParallelGC.
> 
> And for runtimes that are single threaded by nature (e.g. Node) maybe consider a slightly different approach to compare: run two containers for Node at the same time and a third for LB, in a way that this set up equals to the JVM workload in terms of CPU and memory.
> 
> [1] https://www.baeldung.com/jvm-garbage-collectors

This I am not sure. I understand that technologies with GC struggle with single-core benchmark but it's also a valid test (not very real-world, but it's nice to see how different technologies behave under specific conditions). We do try to make it fair by benchmarking also with realistic 3 CPU limit, please look up the [results](https://github.com/LesnyRumcajs/grpc_bench/wiki/2020-08-03-bench-results). From these results it's rather clear which servers should be put behind a LB (e.g. `rust_tonic_st`, `node_grpc_st`) and which scale nicely without this (e.g. `java_grpc`). Adding another set of tests, with LB + single-threaded servers vs Java / Dotnet / Go sounds reallly interesting, thanks for the idea! 

This setting `-XX:+UseParallelGC -XX:+ParallelGCThreads=2` seem to force JVM to use this specific GC, am I correct? This would then hamper the performance for JVM-based benchmarks on 1 CPU, no? Shouldn't then it be chosen automatically, based on benchmark settings? Are those settings optimal for 3 CPUs as well? Feel free to correct me if I'm wrong, I'm not a Java expert. :)

**Comment by LesnyRumcajs** [comment]
@brunoborges current settings seem to have issues on Github Actions, does it work locally for you?
```
Benchmark finished. Detailed results are located in: results/200608T203118
Warning: no stats for reports/kotlin_grpc_test.stats
Warning: no stats for reports/scala_akka_test.stats
Warning: no stats for reports/java_grpc_test.stats
Warning: no stats for reports/java_micronaut_test.stats
----------------------------------------------------------------------------
| name               |   req/s |   avg. latency | avg. cpu |   avg. memory |
----------------------------------------------------------------------------
| rust_tonic_st      |   21650 |        2.26 ms |   44.53% |      5.71 MiB |
| cpp_grpc_st        |   18041 |        2.72 ms |   58.07% |      3.09 MiB |
| go_grpc            |   16282 |        3.01 ms |   66.58% |     12.88 MiB |
| lua_grpc_st        |   15450 |        3.17 ms |   83.05% |     15.01 MiB |
| rust_tonic_mt      |   14432 |        3.39 ms |   82.41% |      6.66 MiB |
| dotnet_grpc        |   14212 |        3.45 ms |   88.31% |     116.1 MiB |
| rust_thruster      |   14062 |        3.49 ms |   67.18% |      2.26 MiB |
| crystal_grpc       |   13417 |        3.67 ms |   48.34% |      5.54 MiB |
| csharp_grpc        |   11570 |        4.26 ms |  100.61% |     79.13 MiB |
| node_grpc_st       |   10309 |        4.78 ms |   91.29% |     23.55 MiB |
| cpp_grpc_mt        |   10060 |        4.90 ms |  124.25% |      5.06 MiB |
| java_aot           |    7196 |        6.90 ms |  118.83% |     100.2 MiB |
| node_grpcjs_st     |    6377 |        7.77 ms |   98.32% |     27.88 MiB |
| php_grpc           |    6318 |        7.85 ms |  117.03% |      48.1 MiB |
| dart_grpc          |    5102 |        9.70 ms |  110.13% |     29.36 MiB |
| elixir_grpc        |    3721 |       13.37 ms |  119.89% |     54.09 MiB |
| swift_grpc_st      |    3681 |       13.50 ms |   98.31% |      4.29 MiB |
| ruby_grpc          |    3481 |       14.20 ms |   87.22% |     18.27 MiB |
| python_grpc        |    2000 |       24.91 ms |   99.95% |     21.64 MiB |
| scala_akka         |       0 |        0.18 ms |       0% |         0 MiB |
| java_micronaut     |       0 |        0.28 ms |       0% |         0 MiB |
| java_grpc          |       0 |        0.28 ms |       0% |         0 MiB |
| kotlin_grpc        |       0 |        0.23 ms |       0% |         0 MiB |
----------------------------------------------------------------------------
```

**Comment by Trisfald** [comment]
These all valid points, but I do agree with @LesnyRumcajs with keeping the defaults 30s/1 cpu for the CI as it's used just to check the correctness. We should instead perform longer duration benchmarks while we produce the results for the wiki. 

About ``ParallelGCThreads maybe we can pass it the number of cpus to the `docker run` command and derive the best value? For instance 1 for cpus < 2, otherwise number of cpus?

**Comment by berestovskyy** [comment]
IMO the hardware limits should be there starting from 1 CPU. We should find a way to go beyond 3 CPUs though, as it seems Java scales really well...

10 minutes per test is a bit too much IMO. @brunoborges do you have any numbers to share running the test 30 s vs 2 min vs 10 min?

**Comment by LesnyRumcajs** [comment]
@berestovskyy 3 CPU is only the limit on our hardware, most of the machine's computing power is taken by gRPC client `ghz`. We'd probably need a 24 core machine to properly stress e.g. `rust_tonic_mt` with server limited to 5.

**Comment by brunoborges** [comment]
@Trisfald it's fair to use X threads (where X = # of CPUs) for the ParallelGC for benchmarks up to 4 cores where heap size is up to 1GB. Beyond that, other GCs should be considered.

**Comment by LesnyRumcajs** [comment]
@brunoborges scala bench still seems to fail, running the container yields:
```
Error: Could not find or load main class $JAVA_OPTS
Caused by: java.lang.ClassNotFoundException: $JAVA_OPT
```

**Comment by Trisfald** [comment]
Shall we perhaps go forward with using the latest LTS in this PR and address the JVM options in another one?

**Comment by brunoborges** [comment]
@LesnyRumcajs I ran a bench here and all worked, except scala.

Just for the record, here are the results I got:

```
GRPC_BENCHMARK_DURATION="300s"
GRPC_SERVER_CPUS="3"
GRPC_SERVER_RAM="512m"

Benchmark finished. Detailed results are located in: results/200808T001153
Warning: no stats for reports/scala_akka_test.stats
----------------------------------------------------------------------------
| name               |   req/s |   avg. latency | avg. cpu |   avg. memory |
----------------------------------------------------------------------------
| go_grpc            |   49413 |        0.96 ms |  229.07% |      13.0 MiB |
| rust_tonic_mt      |   46868 |        1.02 ms |  232.19% |      7.39 MiB |
| cpp_grpc_mt        |   43756 |        1.09 ms |  268.57% |      7.26 MiB |
| rust_tonic_st      |   42496 |        1.12 ms |   97.28% |      6.52 MiB |
| java_grpc          |   41119 |        1.16 ms |  295.16% |     223.1 MiB |
| java_micronaut     |   40661 |        1.18 ms |  298.23% |     248.6 MiB |
| dotnet_grpc        |   36798 |        1.31 ms |   217.9% |     81.08 MiB |
| csharp_grpc        |   29123 |        1.66 ms |  305.09% |     76.83 MiB |
| kotlin_grpc        |   28109 |        1.72 ms |  303.68% |    161.42 MiB |
| cpp_grpc_st        |   27694 |        1.76 ms |  101.31% |      3.22 MiB |
| lua_grpc_st        |   16525 |        2.97 ms |  101.22% |     12.93 MiB |
| java_aot           |   15369 |        3.19 ms |  301.45% |    105.56 MiB |
| node_grpc_st       |   11738 |        4.18 ms |  100.98% |     42.53 MiB |
| php_grpc           |    9597 |        5.15 ms |  305.35% |     38.64 MiB |
| node_grpcjs_st     |    8777 |        5.61 ms |  113.48% |     28.08 MiB |
| elixir_grpc        |    7486 |        6.61 ms |  295.49% |     58.88 MiB |
| dart_grpc          |    7048 |        7.04 ms |  108.55% |     29.11 MiB |
| rust_thruster      |    6445 |        7.68 ms |   72.08% |      2.32 MiB |
| swift_grpc_st      |    4580 |       10.82 ms |    99.8% |      4.05 MiB |
| python_grpc        |    3292 |       15.12 ms |  149.12% |     19.76 MiB |
| ruby_grpc          |    2745 |       18.13 ms |   131.3% |      18.4 MiB |
| crystal_grpc       |    2114 |       23.53 ms |    16.9% |      5.79 MiB |
| scala_akka         |       0 |        0.03 ms |       0% |         0 MiB |
----------------------------------------------------------------------------
```

**Comment by brunoborges** [comment]
I will look into the Scala bug.

**Comment by brunoborges** [comment]
Scala results are in for the same setup:

```
GRPC_BENCHMARK_DURATION="300s"
GRPC_SERVER_CPUS="3"
GRPC_SERVER_RAM="512m"

 Benchmark finished. Detailed results are located in: results/200808T230753
----------------------------------------------------------------------------
| name               |   req/s |   avg. latency | avg. cpu |   avg. memory |
----------------------------------------------------------------------------
| scala_akka         |   11735 |        4.20 ms |  303.77% |    267.56 MiB |
----------------------------------------------------------------------------
```

**Comment by brunoborges** [comment]
And for the record, this is the machine I am using. It is an 8-core VM with 16GB RAM.

```
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz
stepping	: 2
microcode	: 0x43
cpu MHz		: 1197.379
cache size	: 10240 KB
```

**Comment by LesnyRumcajs** [comment]
Looks really good to me, thank you! Faith in Java technology restored. ;)
Let's rebase and then we can merge.

**Comment by brunoborges** [comment]
I got even better results with the latest GA (14), especially in terms of memory consumption.

Given I made several changes beyond just upgrading Java, I'll go ahead and close this PR and submit a new one with less changes beyond upgrading Java and a few JVM settings for this kind of scenario.

**Pull request closed without merging**
