### PR TITLE
Increase number of concurrent connections and requests

### PR DESCRIPTION
**Pull request by JamesNK**
This increases the number of parallel requests being made by the client. RPS and latency both increase.

### CODE REVIEW

**Comment by Trisfald** [comment]
Do we need to change the defaults?  There won't be one set of parameters good for every work load

**Comment by LesnyRumcajs** [comment]
@JamesNK  did you perform some tests with these settings? If yes, could you share the highlights?

**Comment by JamesNK** [comment]
Before
```
GRPC_BENCHMARK_DURATION=30s
GRPC_SERVER_CPUS=3
GRPC_SERVER_RAM=512m
GRPC_CLIENT_CONNECTIONS=5
GRPC_CLIENT_CONCURRENCY=50
GRPC_CLIENT_QPS=0
GRPC_CLIENT_CPUS=5
GRPC_REQUEST_PAYLOAD=100B
-----
Benchmark finished. Detailed results are located in: results/210805T120035
--------------------------------------------------------------------------------------------------------------------------------
| name               |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
--------------------------------------------------------------------------------------------------------------------------------
| dotnet_grpc        |   29202 |        1.64 ms |        1.72 ms |        2.22 ms |       31.54 ms |  241.93% |    109.07 MiB |
| cpp_grpc_mt        |   28979 |        1.65 ms |        1.84 ms |        2.38 ms |       32.78 ms |  251.88% |      22.2 MiB |
| java_grpc_pgc      |   25999 |        1.83 ms |        1.67 ms |        2.44 ms |       51.24 ms |   173.4% |     97.62 MiB |
--------------------------------------------------------------------------------------------------------------------------------
```
After
```
GRPC_BENCHMARK_DURATION=30s
GRPC_SERVER_CPUS=3
GRPC_SERVER_RAM=512m
GRPC_CLIENT_CONNECTIONS=50
GRPC_CLIENT_CONCURRENCY=1000
GRPC_CLIENT_QPS=0
GRPC_CLIENT_CPUS=9
GRPC_REQUEST_PAYLOAD=100B
-----
Benchmark finished. Detailed results are located in: results/210805T114048
--------------------------------------------------------------------------------------------------------------------------------
| name               |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
--------------------------------------------------------------------------------------------------------------------------------
| dotnet_grpc        |   59626 |       16.49 ms |       27.76 ms |       34.61 ms |       55.85 ms |  281.21% |    128.05 MiB |
| cpp_grpc_mt        |   54864 |       17.77 ms |       35.44 ms |       43.34 ms |       64.52 ms |  294.64% |     36.84 MiB |
| java_grpc_pgc      |   46877 |       20.79 ms |       44.25 ms |       56.21 ms |      112.03 ms |  243.75% |    170.68 MiB |
--------------------------------------------------------------------------------------------------------------------------------
```

Quite different overall results from your test runs (i.e. Java way ahead). I'm guessing that's because I'm using Docker on Windows. Or maybe it is because my desktop is Ryzen 🤷

**Comment by LesnyRumcajs** [comment]
@JamesNK Thanks, looks good to me. When I was running some of the earlier benchmarks on MacOS (which uses LinuxKit VM, lightweight one but still) I had some different results as well, like Ruby not cleaning the bottom of the list. :rofl: 

@Trisfald Any objections?

**Review by LesnyRumcajs — APPROVED** [review]

**Review by LesnyRumcajs — CHANGES_REQUESTED** [review]
Actually, one thing that's missing - could you please reflect those changes in the default values in the README file?

**Review by Trisfald — APPROVED** [review]

**Pull request merged**
