### PR TITLE
scala_akka_bench: use latest snapshots

### PR DESCRIPTION
**Pull request by jrudolph**
This includes another optimizations, we plan to get everything released soon.

### CODE REVIEW

**Comment by jtjeferreira** [comment]
before (https://github.com/LesnyRumcajs/grpc_bench/pull/153#issuecomment-872462356)

```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| scala_akka                  |   12475 |       79.54 ms |      134.81 ms |      164.16 ms |      287.94 ms |   71.08% |    164.35 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
``` 

this PR

```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| scala_akka                  |   15637 |       63.48 ms |      102.35 ms |      116.92 ms |      171.96 ms |   45.05% |    205.53 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
```

:clap:

**Comment by jrudolph** [comment]
Interesting, it's a bit different for me.

original, before #153:

```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| rust_tonic_mt               |   35231 |       28.25 ms |       12.65 ms |       13.90 ms |      727.31 ms |  101.99% |      14.2 MiB |
| scala_akka                  |    6154 |      161.41 ms |      293.17 ms |      396.36 ms |      744.06 ms |  101.59% |    256.73 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
Benchmark Execution Parameters:
[...]
- GRPC_BENCHMARK_DURATION=30s
- GRPC_BENCHMARK_WARMUP=30s
- GRPC_SERVER_CPUS=1
- GRPC_SERVER_RAM=512m
- GRPC_CLIENT_CONNECTIONS=50
- GRPC_CLIENT_CONCURRENCY=1000
- GRPC_CLIENT_QPS=0
- GRPC_CLIENT_CPUS=9
- GRPC_REQUEST_PAYLOAD=100B
+ echo 'All done.'
All done.
```

after #153:

```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| rust_tonic_mt               |   33852 |       29.40 ms |       13.61 ms |       15.16 ms |      716.89 ms |  100.74% |     13.78 MiB |
| scala_akka                  |   20435 |       48.71 ms |       90.23 ms |      100.03 ms |      172.59 ms |  100.91% |    247.53 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
Benchmark Execution Parameters:
2a00721 Thu, 1 Jul 2021 20:40:10 +0200 LesnyRumcajs scala_akka: update to latest versions and fix some settings
- GRPC_BENCHMARK_DURATION=30s
- GRPC_BENCHMARK_WARMUP=30s
- GRPC_SERVER_CPUS=1
- GRPC_SERVER_RAM=512m
- GRPC_CLIENT_CONNECTIONS=50
- GRPC_CLIENT_CONCURRENCY=1000
- GRPC_CLIENT_QPS=0
- GRPC_CLIENT_CPUS=9
- GRPC_REQUEST_PAYLOAD=100B
All done.
```

with this PR:

```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| rust_tonic_mt               |   34746 |       28.65 ms |       12.95 ms |       14.22 ms |      728.89 ms |  101.68% |     13.56 MiB |
| scala_akka                  |   29508 |       33.68 ms |       72.79 ms |       81.94 ms |       99.76 ms |  101.35% |    227.33 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
Benchmark Execution Parameters:
4ec339b Mon, 12 Jul 2021 10:25:15 +0200 Johannes Rudolph use latest snapshots
- GRPC_BENCHMARK_DURATION=30s
- GRPC_BENCHMARK_WARMUP=30s
- GRPC_SERVER_CPUS=1
- GRPC_SERVER_RAM=512m
- GRPC_CLIENT_CONNECTIONS=50
- GRPC_CLIENT_CONCURRENCY=1000
- GRPC_CLIENT_QPS=0
- GRPC_CLIENT_CPUS=9
- GRPC_REQUEST_PAYLOAD=100B
All done.

```

**Review by Trisfald — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
Thanks! Looking forward for the release! :)

**Comment by jtjeferreira** [comment]
@jrudolph the numbers I pasted are just from github actions running the benchmarks for the PR...

**Comment by jrudolph** [comment]
> @jrudolph the numbers I pasted are just from github actions running the benchmarks for the PR...

Ah cool, good to know.

**Pull request merged**
