### PR TITLE
Update .NET and gRPC package versions

### PR DESCRIPTION
**Pull request by JamesNK**

### CODE REVIEW

**Comment by MCCshreyas** [comment]
Ohh @JamesNK, I did the same. Hahhahhaa

**Comment by MCCshreyas** [comment]
I will close my PR now.

**Comment by MCCshreyas** [comment]
Btw, why there is a separate CSharp version here in the repo other than the dotnet version?

**Comment by JamesNK** [comment]
dotnet_grpc_bench = Grpc.AspNetCore
csharp_grpc_bench = Grpc.Core (this wraps C++ implementation and the .NET version doesn't have much impact on performance)

**Comment by LesnyRumcajs** [comment]
@JamesNK thank you!

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
