### PR TITLE
Erlang implementation with grpcbox

### LINKED ISSUE #22: Add Erlang benchmark
Add an Erlang grpc benchmark.

The library is here: https://github.com/bluehouse-technology/grpc

- [ ] gRPC server implementation
- [ ] Dockerfile to build an image with the gRPC server
- [ ] update build.sh, clean.sh and bench.sh scripts

### PR DESCRIPTION
**Pull request by fenollp**
* [x]  gRPC server implementation
* [x]  Dockerfile to build an image with the gRPC server
* [x]  update build.sh, clean.sh and bench.sh scripts

I have made some changes to the shell scripts solely to show progress during build/bench-ing.

Fixes #22

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@fenollp Thank you for the contribution! Looks good to me, though I didn't expect that Erlang would need so many files, good I didn't even try. :)

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
@fenollp Looking at the stdout in the CI, it seems we have a nice race, most likely coming from the change in `build.sh` (not sure). Perhaps let's discard those verbose output changes in this PR?

**Comment by fenollp** [comment]
Sure, I'll do this today.

I guess the race condition is just because jobs are started in parallel:
```
2021-05-04T17:25:33.9658607Z ==> Building Docker image for cpp_grpc_mt_bench...
2021-05-04T17:25:33.9659398Z ==> Building Docker image for cpp_grpc_st_bench...
2021-05-04T17:25:33.9660159Z ==> Building Docker image for crystal_grpc_bench...
2021-05-04T17:25:33.9660915Z ==> Building Docker image for csharp_grpc_bench...
2021-05-04T17:25:33.9661635Z ==> Building Docker image for dart_grpc_bench...
2021-05-04T17:25:33.9662625Z ==> Building Docker image for dotnet_grpc_bench...
2021-05-04T17:25:33.9663369Z ==> Building Docker image for elixir_grpc_bench...
2021-05-04T17:25:33.9664356Z ==> Building Docker image for erlang_grpcbox_bench...
2021-05-04T17:25:33.9665085Z ==> Building Docker image for go_grpc_bench...
2021-05-04T17:25:33.9665862Z ==> Building Docker image for haskell_mu_bench...
2021-05-04T17:25:33.9666586Z ==> Building Docker image for java_aot_bench...
2021-05-04T17:25:33.9667317Z ==> Building Docker image for java_grpc_g1gc_bench...
2021-05-04T17:25:33.9668051Z ==> Building Docker image for java_grpc_pgc_bench...
2021-05-04T17:25:33.9668801Z ==> Building Docker image for java_grpc_sgc_bench...
2021-05-04T17:25:33.9669526Z ==> Building Docker image for java_grpc_she_bench...
2021-05-04T17:25:33.9670271Z ==> Building Docker image for java_grpc_zgc_bench...
2021-05-04T17:25:33.9671014Z ==> Building Docker image for java_micronaut_bench...
2021-05-04T17:25:33.9671772Z ==> Building Docker image for kotlin_grpc_bench...
2021-05-04T17:25:33.9672528Z ==> Building Docker image for lua_grpc_st_bench...
2021-05-04T17:25:33.9673210Z ==> Waiting for the builds to finish...
```
after all my change is only to use `tee` so it was always racy. Build doesn't fail though :)

**Comment by Trisfald** [comment]
CI is failing because of lua, can you rebase this branch on master (we disabled lua temporarily)?

**Comment by fenollp** [comment]
@Trisfald Rebased.

**Comment by fenollp** [comment]
I'll comment-out the `fmt` step if it's too annoying then.

**Comment by Trisfald** [comment]
great!

**Pull request merged**
