### PR TITLE
[fix] added vertx multiple-core support

### PR DESCRIPTION
**Pull request by gcnyin**
**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

**Other information and links**

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@gcnyin Should this also be addressed here? https://github.com/LesnyRumcajs/grpc_bench/issues/360

**Comment by He-Pin** [comment]
i think this will only make it scale with more cores

**Comment by LesnyRumcajs** [comment]
> i think this will only make it scale with more cores

It's good, no? But I'm okay with doing it in another PR.

**Review by LesnyRumcajs — APPROVED** [review]
thanks!

**Pull request merged**
