### PR TITLE
Some benchs are nonblocking, so use a direct executor for Java benchs

### PR DESCRIPTION
**Pull request by brunoborges**

### CODE REVIEW

**Comment by brunoborges** [comment]
@Trisfald correct, and why #81 is so important. Otherwise, each bench is only aiming at being fast within loose rules.

**Comment by brunoborges** [comment]
@Trisfald which benchs are implemented with non-blocking? AFAICT, Node is. And I think Go/Rust/.NET too, no?

**Comment by Trisfald** [comment]
@brunoborges Rust uses a thread pool with work stealing (equivalent of `ForkJoinPool`?). C++ implementation is super simple, just a vector of threads racing between themselves :). In general, they don't suffer from the disadvantages highlighted here: https://github.com/grpc/grpc-java/issues/5185#issuecomment-448707858
About .NET, Go or Node.js I don't have the knowledge.

**Comment by brunoborges** [comment]
Isn't the goal of this benchmark to evaluate which runtime/language implements the said proto GRPC service faster? Because if the use case is simply returning a hello world, then we could go ahead and implement each one however possible to get the best result for this particular workload.

If the goal is to identify realistic metrics, then the benchmark should probably reconsider the use case being evaluated.

**Comment by Trisfald** [comment]
Yes, the original goal was to identify which implementation is faster. Maybe the hello world example is not ideal, we can iterate on that. The question is: should the test be able to handle all workloads? (blocking and non-blocking).  In my opinion I'd say we should have a generic bench able to handle everything and then specialized benches for particular situations. 
If Java has a `directExecutor` for very specific workload, it should be included in the bench. However, it shouldn't replace the generic implementation. 
An alternative is to have more **categories**. For instance: fastest "generic", fastest non-blocking, fastest single threaded.

**Comment by LesnyRumcajs** [comment]
Yes, the `hello` proto is not ideal indeed but it allowed us to spawn a lot of benchmarks without really knowing the languages, mostly just `copy-pasting` from the examples and contriving a nice, cozy Dockerfile. We could iterate and e.g. benchmark a small in-memory `database` with a simple HashMap. But that'd be probably another set of benches. 

We should strive to have generic, general-purpose implementations for others to not only compare but possibly copy for their own purposes and extend upon. Perhaps each implementation should have comments, tags on e.g. blocking and non-blocking, or some other limitations. 

I got this week kind of busy, sorry. I hope to make a proposal for https://github.com/LesnyRumcajs/grpc_bench/issues/81 next week. 

@brunoborges I see you are very active and I really appreciate you sharing your expertise with us. Would you like me to add you as as this repo collaborator?

**Comment by brunoborges** [comment]
@LesnyRumcajs no worries on the busy work, that's totally understandable :-) 

Thanks for inviting me to collaborate on this project. It will be a pleasure to contribute further.

**Comment by brunoborges** [comment]
By the way, this PR can be closed. We can work with #94 instead.

Once that's merged, I'll submit the benchs for the different combinations of GC and Executors.

**Comment by LesnyRumcajs** [comment]
@brunoborges Thank you! I've just sent you an invite.

**Pull request closed without merging**
