### PR TITLE
using latest OpenJDK17 and Gradle 7.3

### PR DESCRIPTION
**Pull request by liyuntao**
Upgrade to jdk17 for a free performance boost (java17 supported by Gradle >= 7.3)

Change OpenJDK base image from adoptOpenJdk to [bellsoft/liberia-openjdk](https://hub.docker.com/u/bellsoft), based on [discussions for choosing distribution](https://www.reddit.com/r/java/comments/hbywy1/comment/fvbycj0/?utm_source=share&utm_medium=web2x&context=3)

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
Hm, I think I'll let @brunoborges pronounce on this, I have no knowledge on those different jdks.

**Comment by brunoborges** [comment]
That discussion is 2 years old.

And while Liberica JDK is as good as Adoptium, it is still a vendor-specific distribution, while AdoptOpenJDK has moved to the Eclipse Foundation (last year) and is truly vendor neutral, with companies like Red Hat, IBM, and Microsoft supporting it.

If anything I'd suggest to upgrade to Eclipse Adoptium builds of OpenJDK: Temurin 17.

**Comment by LesnyRumcajs** [comment]
@brunoborges Thanks a lot for the detailed answer! Glad I asked you. :)

@liyuntao could you please look into this? Seems this Eclipse Foundation JDK is the way to go.

**Comment by liyuntao** [comment]
Hey @brunoborges @LesnyRumcajs 
Thanks for the detailed explanation. Adoptium is indeed a more appropriate choice

With the latest commit, the base JDK image has been replaced with `eclipse-temurin:17`, and almost all JVM projects will compile to the newest bytecode.

**Comment by brunoborges** [comment]
Awesome!

@LesnyRumcajs you have my +1 for this commit.

**Comment by brunoborges** [comment]
Any chance you can run this benchmark to compare with and without these flags?

**Comment by liyuntao** [comment]
> Any chance you can run this benchmark to compare with and without these flags?

Not yet, I don't have a stable high-performance workstation on hand, just some VM-based development machine.

I only run a few times here to verify that the commits are not breaking.

**Comment by brunoborges** [comment]
> > Any chance you can run this benchmark to compare with and without these flags?
> 
> Not yet, I don't have a stable high-performance workstation on hand, just some VM-based development machine.
> 
> I only run a few times here to verify that the commits are not breaking.

I think it is still worth running anyways. What we care about is the delta.

**Review by Trisfald — APPROVED** [review]

**Comment by jtjeferreira** [comment]
Can you also upgrade the scala benchmarks?

**Comment by brunoborges** [comment]
To be clear, I am not comfortable with merging this pull request until someone shows the delta due to the introduction of these two JVM parameters.

Moving to Java 17 is a must. But blindly optimizing the JVM without a preliminary benchmark result, is not great.

**Comment by liyuntao** [comment]
Well, in that case, I'll roll back the commit first.

**Comment by LesnyRumcajs** [comment]
@liyuntao could you please update Scala benches images as well? @jtjeferreira has a good point as they are also using this image you upgraded.

**Comment by liyuntao** [comment]
@brunoborges To be clear, I am also not comfortable with parts of your remarks. It makes me feel the project is **not open for PR outside a small circle of people**. Even such fine-grained minor commits would result to subjective, ambiguous criteria argument and repeatedly procrastinating. 

@LesnyRumcajs Well, I'm not interested now. The PR will be closed unless anybody who really thinks moving to JDK 17 is a must and is willing to move his/her little finger, personally.

**Comment by LesnyRumcajs** [comment]
@liyuntao Sorry to hear that! Could you please elaborate on why bumping the image version in every concerned suite was unreasonable to ask? I mean, it's even easier to replace it everywhere than only in a subset or am I missing something?

**Comment by liyuntao** [comment]
@LesnyRumcajs <https://github.com/LesnyRumcajs> Whether a JVM project can
really support bytecode version17 depends on the specific language,
including its version number and application framework support. I'm not
sure about the Scala project can support bytecode version 17 directly, and
only tested the parts I changed at first.

Close the PR only because I don't like the Java reviewer guy, not your
fault.

**Pull request closed without merging**
