### PR TITLE
fix bench and add example script

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
**Summary of changes**
Changes introduced in this pull request:
- add sample benchmarking script,
- remove caching that was behaving funny and producing lots of errors. Probably will need to find an alternative or a proper fix if it becomes a kind of bottleneck.

**Reference issue to close (if applicable)**

**Other information and links**

### CODE REVIEW

**Comment by fenollp** [comment]
> remove caching that was behaving funny and producing lots of errors. Probably will need to find an alternative or a proper fix if it becomes a kind of bottleneck.

Can you share CI runs exhibiting this please? I'd like to take a look.

**Comment by LesnyRumcajs** [comment]
Hi @fenollp. I didn't notice this happening in the CI but on a fresh VPS when building all of the images. Interestingly, when trying to build a single image, it would succeed. My wild guess is that there is some kind of a race condition, though it's just speculation. 

Here's the error log from my machine (Fedora 36, though I had the same issue on a Ubuntu 22.04 VPS).
[cache_error.txt](https://github.com/LesnyRumcajs/grpc_bench/files/9692806/cache_error.txt)

**Comment by fenollp** [comment]
Indeed the `unexpected EOF` issues seem to be related to BuildKit's `BUILDKIT_INLINE_CACHE=1`.

I've found a couple issues on their bugtracker around these symptoms with merged PRs as the outcome.

Can it be that you're running an older docker engine? Latest is: https://docs.docker.com/engine/release-notes/#201018

Note: removing these cache directives should make build jobs run longer (in theory. I see the actions in this PR seem to run pretty fast anyway).

Yeah, no idea what's going on here really. It'd be nice to have a reproducer to send to BuildKit. In any case it seems harmless to drop these directives. Doing so though I'd suggest removing the code that pushes the docker images as well, as these are of no use anymore.

**Comment by LesnyRumcajs** [comment]
@fenollp Thanks for looking into it! I believe I am using a quite recent docker release, `20.10.18`. I can't say I fully get what is happening. Issuing a bug for `buildkit` seems like a good idea, I may do that later!

**Comment by LesnyRumcajs** [comment]
@fenollp By the way, would you like to be added to the repo collaborators? No pressure of course! I believe it's only fair after your outstanding contributions. :)

**Comment by fenollp** [comment]
Yes, sure :)

**Pull request merged**
