### PR TITLE
Add Armeria benchmark

### PR DESCRIPTION
**Pull request by ikhoon**
[Armeria](https://armeria) is yet another a gRPC server and client
framewrok for JVM launguages such as Java, Kotlin and Scala.
I'd like to add a benchmark for Armeria.
Please see https://armeria.dev/docs/server-grpc for Armeria gRPC server.

### CODE REVIEW

**Review by LesnyRumcajs — COMMENTED** [review]
Hello and thank you! It looks good, though unfortunately, the CI for this one is not passing. One other thing, I don't see the implementation handling the CPUs variable which may hurt the performance. Maybe it's done in your case behind the scenes but it may be worth looking into. See an example with [Quarkus](https://github.com/LesnyRumcajs/grpc_bench/blob/0dd889b039b68c15521d771ecee1c308796f15aa/java_quarkus_bench/Dockerfile#L13)

**Comment by ikhoon** [comment]
> the CI for this one is not passing.

Oops... let me take a look.

> Maybe it's done in your case behind the scenes but it may be worth looking into.

Thanks for the tip. I don't think we need to pass the CPUs variable manually. The number of CPU is automatically detected by JDK's API that is used for the default working group.
https://github.com/line/armeria/blob/c7b37b2bd52eab185340866a9430cc0a2b1770b5/core/src/main/java/com/linecorp/armeria/common/Flags.java#L101

**Comment by ikhoon** [comment]
The test seems to be passed after upgrading `Protobuf` plugin version.. https://github.com/ikhoon/grpc_bench/runs/5715091169?check_suite_focus=true

**Comment by LesnyRumcajs** [comment]
> Thanks for the tip. I don't think we need to pass the CPUs variable manually. The number of CPU is automatically detected by JDK's API that is used for the default working group.

Yes, but I'm not sure it will detect it correctly. I believe in a containerized environment the CPU count will be detected as host CPU count, regardless of what limits you put on the container. Something to consider and play with perhaps, that's why we exposed as separate environment variable.

**Comment by LesnyRumcajs** [comment]
> The test seems to be passed after upgrading `Protobuf` plugin version.. https://github.com/ikhoon/grpc_bench/runs/5715091169?check_suite_focus=true

Rock-solid, thanks!

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
