### PR TITLE
fix erlang and elixir builds

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
* fallback to commented out grpc dependency for Elixir
* obliterate lock files so dependencies can figure out their versions

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@sleipnir @fenollp The builds were failing, did my best effort without knowing those technologies to make it green. Feel free to push to this branch or submit a PR with a better solution. :)

**Comment by sleipnir** [comment]
Hi @LesnyRumcajs sorry about that, we renamed our fork from the original library.
Tomorrow I promise to take a look at this and send a PR with the fix

**Comment by LesnyRumcajs** [comment]
> Hi @LesnyRumcajs sorry about that, we renamed our fork from the original library. Tomorrow I promise to take a look at this and send a PR with the fix

Hello @sleipnir , no worries, whenever you have some spare time.

**Comment by fenollp** [comment]
I'm not a fan of removing the lockfiles so I fixed the Erlang one but you do you.

If you'd be fine with keeping lockfiles it could be on the condition that we have an easy way of updating them.
We could add a target to Dockerfiles so that an update.sh script could just rewrite the lockfile when asked.

```shell
docker build -o erlang_grpcbox_bench/ -f erlang_grpcbox_bench/Dockerfile
```

```diff
diff --git a/erlang_grpcbox_bench/Dockerfile b/erlang_grpcbox_bench/Dockerfile
index 787bd46..1e2e01d 100644
--- a/erlang_grpcbox_bench/Dockerfile
+++ b/erlang_grpcbox_bench/Dockerfile
@@ -17,3 +17,14 @@ COPY --from=builder /opt/rel .
 EXPOSE 50051
 ENTRYPOINT ["/app/bin/erlang_grpcbox_bench"]
 CMD ["foreground"]
+
+
+FROM erlang as do-update
+WORKDIR /app
+COPY erlang_grpcbox_bench /app
+RUN rebar3 do update, upgrade
+RUN rebar3 plugins upgrade
+RUN rebar3 unlock && rebar3 lock
+
+FROM scratch AS update
+COPY --from=do-update /app/rebar.lock /
```

**Comment by LesnyRumcajs** [comment]
Hello @fenollp . I have no problems with lockfiles (for binaries in general they should be there), just wanted to make it pass. That's why I pinged you, I don't want to make Erlang or any other technology look bad. :)

**Comment by sleipnir** [comment]
@LesnyRumcajs thanks for that and I'm sorry for being late

**Pull request merged**
